name: Deploy Database Pipeline

on: 
  push:
    paths:
      - 'k8s/database/**'
  workflow_run:
    workflows: [ "Terraform Infra Pipeline" ]
    types:
      - completed
  workflow_dispatch:

env: 
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: dev-eks-cluster
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    name: Deploy Database
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code 
        uses: actions/checkout@v3 

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Deploy to EKS 
        run: |
          kubectl apply -f ./k8s/database/pv-claim.yaml 
          kubectl apply -f ./k8s/database/deployment.yaml 
          kubectl apply -f ./k8s/database/service.yaml 
