name: Terraform Infra Pipeline

on:
  push:
    paths:
      - 'terraform/**'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  S3_BUCKET_NAME: dev-environment-state-lock-bucket-nyaay-mitra
  EKS_CLUSTER_NAME: dev-eks-cluster
  ECR_REPO_NAME: dev-ecr-repo

jobs:
  terraform: 
    name: Terraform CICD Pipeline 
    runs-on: ubuntu-latest 

    defaults:
      run: 
        working-directory: terraform/environments/dev

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3 

      - name: Setup Terrform 
        uses: hashicorp/setup-terraform@v3 

      - name: Ensure backend bucket exist
        run: |
          aws s3api head-bucket --bucket $S3_BUCKET_NAME || \
          aws s3api create-bucket --bucket $S3_BUCKET_NAME --region $AWS_REGION
      
      - name: Terraform init
        run: terraform init 

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Terraform Plan
        run: terraform plan -input=false  -lock=false 
      
      # - name: Terraform Apply 
      #   run: terraform apply -input=false --auto-approve

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Delete Ingress manually (workaround for destroy error)
        run: |
          kubectl delete ingress frontend-ingress -n default || echo "Ingress not found, continuing"
      
      - name: Terraform Destroy 
        run: terraform destroy -input=false --auto-approve -lock=false
      
  