name: Terraform Infra Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform: 
    name: Terraform CICD Pipeline 
    runs-on: ubuntu-latest 

    defaults:
      run: 
        working-directory: terraform/environments/dev

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3 

      - name: Setup Terrform 
        uses: hashicorp/setup-terraform@v3 
      
      - name: Terraform init
        uses: terraform init 

      - name: Terraform Format
        uses: terraform fmt -recursive

      - name: Terraform Plan
        uses: terraform plan -input=false 
      
      - name: Terraform Apply 
        uses: terraform apply -input=false --auto-approve
      
  